RUN = "run"
REQUEST_ID = "request_id"
NODE = "node"
EVENT = "event"
TS = "ts"
UDF_MS = "udf_ms"

RESTPP_NODE = "restpp_node"
RESTPP_TS = "restpp_ts"
RESTPP_RETURN_TS = "restpp_return_ts"
RESTPP_RETURN_MS = "restpp_return_ms"
QUERY_NAME = "query_name"
GRAPH_NAME = "graph_name"
ENDPOINT = "endpoint"

GPE_NODE = "gpe_node"
FIRST_SEEN_GPE_TS = "first_seen_gpe_ts"
LAST_SEEN_GPE_TS = "last_seen_gpe_ts"
START_UDF_TS = "start_udf_ts"
STOP_UDF_TS = "stop_udf_ts"
REPORTED_STOP_UDF_MS = "reported_stop_udf_ms"

ACTUAL_STOP_UDF_MS = "actual_stop_udf_ms"
ACTUAL_DIFF_FIRST_LAST_SEEN_MS = "actual_diff_first_last_seen_ms"
DIFF_GPE_DURATION_UDF_MS = "diff_gpe_duration_udf_ms"

FIRST_SEEN_TS_RESTPP = "first_seen_ts_restpp"
SYNC_RETURN_TS_RESTPP = "sync_return_result_ts_restpp"
SYNC_RETURN_TIME_MS = "sync_return_time_ms"
FULL_ENDPOINT = "full_endpoint"
ENDPOINT_NAME = "endpoint_name"
